name: Deploy to the web environment

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tungtk99/my-blog-web-fe:latest
      
      - name: Execute command on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: tungtk
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull tungtk99/my-blog-web-fe:latest
            sudo docker stop $(docker ps -aq)
            sudo docker rm $(docker ps -aq)
            sudo docker rmi $(docker images -q)
            sudo docker system prune -a
            sudo docker pull tungtk99/my-blog-web-fe:latest
            sudo docker run -d --name my-blog-fe-app tungtk99/my-blog-web-fe:latest