name: Deploy to the web environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: tungtk99/my-blog-web-fe:latest
      
      - name: Execute command on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ${{ secrets.SSH_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} << 'EOF'

            # Now we have got the access of EC2 and we will start the deploy .
            sudo docker pull tungtk99/my-blog-web-fe:latest
            sudo docker stop $(sudo docker ps -aq)
            sudo docker rm $(sudo docker ps -aq)
            sudo docker rmi $(sudo docker images -q)
            sudo docker system prune -a -f
            sudo docker pull tungtk99/my-blog-web-fe:latest
            sudo docker run -d -p 8000:3000 --name my-blog-fe-app tungtk99/my-blog-web-fe:latest
          EOF